video:
  camera_index: 0
  mirror_view: true
  draw_landmarks: false
mediapipe:
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  refine_landmarks: true
thresholds:
  EAR_THRESHOLD: 0.25
  EAR_CONSEC_FRAMES: 15
  MAR_THRESHOLD: 0.6
  MAR_CONSEC_FRAMES: 10
  HEAD_TILT_DEG: 18.0
  TILT_CONSEC_FRAMES: 15
  NO_FACE_SECONDS: 2.0
  ALARM_COOLDOWN_SECONDS: 3.0
logging:
  enable_csv: true
  csv_path: events_log.csv
